lib/presence_chat_web/router.ex
defmodule PresenceChatWeb.Router do
  use PresenceChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PresenceChatWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/login", SessionController, :new

    resources "/sessions", SessionController,
      only: [:new, :create, :delete],
      singleton: true

    # get "/chats/search", SearchChatController, :index

    live "/chats/search", SearchChatsLiveView, session: [:user_id]
    live "/chats/:id", ChatLiveView, session: [:user_id]
    get "/sign-up", UserController, :new
    # live “/users/new”, UserLive.New
    # resources "/users", UserController
    # resources "/chats", ChatController
    # resources "/messages", MessageController
    # resources "/memberships", MembershipController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PresenceChatWeb do
  #   pipe_through :api
  # end
end

lib/presence_chat_web/views/search_chats_view.ex
defmodule PresenceChatWeb.SearchChatsView do
  use PresenceChatWeb, :view

  def elipses(true), do: "..."
  def elipses(false), do: nil

  def initials(user) do
    [user.first_name, user.last_name]
    |> Enum.map(&(String.first(&1) |> String.capitalize()))
  end

  def full_name(user) do
    "#{user.first_name} #{user.last_name}"
  end

  def avatar_image_url(user), do: avatar_image_url(user, [size: 50])
  def avatar_image_url(user, [size: size]) do
    "https://robohash.org/#{user.first_name}_#{user.last_name}.jpg?bgset=bg2&size=#{size}x#{size}"
  end

  def format_datetime(i) do
    NaiveDateTime.to_string(i)
  end

  def status_class(users, user) do
    case find_user(users, user) do
      %{away: false} ->
        "online"

      %{away: true} ->
        "away"

      _ ->
        "offline"
    end
  end

  def typing_class(users, user) do
    case find_user(users, user) do
      %{typing: true} ->
        "typing"

      _ ->
        ""
    end
  end

  def find_user(users, user) do
    Enum.find(users, fn o ->
      case user do
        %{user_id: _} = user ->
          o.user_id == user.user_id

        user ->
          o.user_id == user.id
      end
    end)
  end

  def sorted_chat_users(chat, users) do
    online_members = Enum.filter(chat.members, fn member -> status_class(users, member) == "online" end)
    online_visitors = Enum.reject(users, fn user -> user.away || Enum.any?(online_members, fn member -> member.id == user.user_id end) end)
    away_members = Enum.filter(chat.members, fn member -> status_class(users, member) == "away" end)
    away_visitors = Enum.reject(users, fn user -> !user.away || Enum.any?(chat.members, fn member -> member.id == user.user_id end) end)
    offline_members = Enum.filter(chat.members, fn member -> status_class(users, member) == "offline" end)

    online_members ++ online_visitors ++ away_members ++ away_visitors ++ offline_members
  end
end

lib/presence_chat_web/templates/search_chats/index.html.leex
<div class="container">
<%= if @new_chat.action do %>
  <div class="toast toast-error">
    <button class="btn btn-clear float-right"></button>
    <%= gettext("Oops, something went wrong! Please check the errors below.") %>
  </div>
<% end %>

  <h1><%= gettext("Bots Chats") %></h1>

  <div class="columns">
    <div class="column col-12">

    <%= form_for :search, "#", [phx_change: :search, phx_submit: :search], fn f -> %>
      <div class="input-group">
        <span class="input-group-addon addon-lg">
          <i class="form-icon icon icon-search"></i>
        </span>
        <%= text_input f, :query, value: @search.query, autofocus: true, class: "form-input input-lg", placeholder: gettext("Start to type chat name here...") %>
        <%= submit gettext("Search"), class: "btn btn-primary input-group-btn btn-lg" %>
      </div>
    <% end %>

    </div>
  </div>

  <div class="columns">
    <%= for chat <- @chats do %>
    <div class="column col-6 col-md-12 py-2">
      <div class="card">
        <div class="card-header">
          <div class="card-title h5">
            <div class="tile tile-centered">
              <div class="tile-icon">
                <span class="chip"><%= chat.name %></span>
              </div>
              <div class="tile-content text-right">
                <% users = @users[chat.id] %>
                <% user_list = sorted_chat_users(chat, users) %>

                <%= for user <- user_list do %>
                  <figure class="avatar avatar-sm" data-initial="<%= initials(user) %>" style="background-color: #5755d9;">
                    <img src="<%= avatar_image_url(user) %>" alt="<%= gettext("Avatar for user %{full_name}", full_name: full_name(user)) %>">
                    <i class="avatar-presence <%= status_class(users, user) %> <%= typing_class(users, user) %>"></i>
                  </figure>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body">
          <% recent_message = @recent_messages[chat.id] %>
          <%= if recent_message != nil do %>
          <% user = recent_message.author %>
          <div class="tile tile-centered">
            <div class="tile-icon">
              <figure class="avatar avatar-xl" data-initial="<%= initials(user) %>" style="background-color: #5755d9;">
                <img src="<%= avatar_image_url(user) %>" alt="<%= gettext("Avatar for user %{full_name}", full_name: full_name(user)) %>">
                <i class="avatar-presence <%= status_class(users, user) %> <%= typing_class(users, user) %>"></i>
              </figure>
            </div>
            <div class="tile-content">
              <div class="tile-title">
                <%= recent_message.body %>
              </div>
              <small class="tile-subtitle text-gray"><%= format_datetime(recent_message.inserted_at) %></small>
            </div>
          </div>
          <% end %>
        </div>
        <div class="card-footer">
          <div class="btn-group btn-group-block">
            <%= link gettext("View"), to: Routes.live_path(@socket, PresenceChatWeb.ChatLiveView, chat), data: [phx_live_link: "push"], class: "btn btn-primary" %>
          </div>
          <%# <button class="btn btn-primary">...</button> %>
        </div>
      </div>
    </div>
    <% end %>

    <%= if Enum.empty?(@chats) do %>
      <div class="column col-12">
        <div class="empty">
          <div class="empty-icon">
            <i class="icon icon-3x icon-flag"></i>
          </div>
          <p class="empty-title h5">
            <%= gettext("No existing chats found") %>
          </p>
          <p class="empty-subtitle">
            <%= gettext("You can create create new one to start conversation.") %>
          </p>
          <div class="empty-action">
            <%= form_for @new_chat, "#", [phx_submit: :create_chat, csrf_token: @csrf_token], fn f -> %>
              <div class="form-group col-3 col-sm-10 col-md-6 col-lg-4 col-mx-auto <%= if @new_chat.action, do: "has-error", else: "" %>">
                <%= text_input f, :name, value: @search.query, class: "form-input input-lg text-center", placeholder: "Enter name here...", required: true %>
                <%= error_tag f, :name %>
              </div>

              <%= submit gettext("Create new chat"), class: "btn btn-primary input-group-btn btn-lg" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<span><%# link "New Chat", to: Routes.chat_path(@conn, :new)</span> %>